# Generated by Django 4.0.2 on 2022-02-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='heldBook',
            field=models.IntegerField(default=0),
        ),
    ]
